import type { Metadata } from "next";
import "@/styles/globals.css";
import verifySession from "@/lib/auth/verify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  dashboard,
  login,
}: {
  dashboard: React.ReactNode;
  login: React.ReactNode;
}) {

  const isAuthenticated = await verifySession();

  return (
    <html lang="pt-br">
      <body>{isAuthenticated.success ? dashboard : login}</body>
    </html>
  );
}
