import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  dashboard,
  login,
}: {
  dashboard: React.ReactNode;
  login: React.ReactNode;
}) {

  const isAuthenticated = true

  return (
    <html lang="pt-br">
      <body>{isAuthenticated ? dashboard : login}</body>
    </html>
  );
}
