import type { Metadata } from 'next'
import verifySession from "@/lib/auth/verify";
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  dashboard,
  login,
}: {
  dashboard: React.ReactNode;
  login: React.ReactNode;
}) {

  const isAuthenticated = await verifySession();

  return (
    <html lang="pt-br">
      <body>{isAuthenticated.success ? dashboard : login}</body>
    </html>
  );
}
